** Children of Abraham
   :PROPERTIES:
   :CUSTOM_ID: children-of-abraham
   :END:

*** Scriptures: preliminary
    :PROPERTIES:
    :CUSTOM_ID: scriptures-preliminary
    :END:

- Abraham source in all 3
- Genesis 12
- Question: the same God?

  - Elohim, YHWH
  - Father, Son, Holy Spirit
  - Allah

Note: References to Abraham in the Quran[edit]
[[https://en.wikipedia.org/wiki/Abraham_in_Islam#References_to_Abraham_in_the_Quran]]
There are numerous references to Abraham in the Quran, including, twice,
to the Scrolls of Abraham;[62] in the latter passage, it is mentioned
that Abraham "fulfilled his engagements?-",[63] a reference to all the
trials that Abraham had succeeded in. In a whole series of chapters, the
Quran relates how Abraham preached to his community as a youth and how
he specifically told his father, named Azar,[64] to leave idol-worship
and come to the worship of God.[65] Some passages of the Quran,
meanwhile, deal with the story of how God sent angels to Abraham with
the announcement of the punishment to be imposed upon Lot's people in
Sodom and Gomorrah.[66] Other verses mention the near-sacrifice of
Abraham's son,[28] whose name is not given but is presumed to be Ishmael
as the following verses mention the birth of Isaac.[67] The Quran also
repeatedly establishes Abraham's role as patriarch and mentions numerous
important descendants who came through his lineage, including Isaac,[68]
Jacob[69] and Ishmael.[70] In the later chapters of the Quran, Abraham's
role becomes yet more prominent. The Quran mentions that Abraham and
Ishmael were the reformers who set up the Kabba in Mecca as a center of
pilgrimage for monotheism[71] The Quran consistently refers to Islam as
"the Religion of Abraham" (millat Ibrahim)[72] and Abraham is given a
title as Hanif (The Pure, "true in Faith" or "upright man").[73] The
Quran also mentions Abraham as one whom God took as a friend
(Khalil),[38] hence Abraham's title in Islam, Khalil-Allah (Friend of
God). The term is considered by some to be a derivation of the
patriarch's Hebrew title, Kal El (קל-אל), which means "voice of
God".[74][75] Other instances in the Quran which are described in a
concise manner are the rescue of Abraham from the fire into which he was
thrown by his people';[76][77] his pleading for his father;[78] his
quarrel with an unrighteous and powerful king[79] and the miracle of the
dead birds.[31]

--

*** Scriptures
    :PROPERTIES:
    :CUSTOM_ID: scriptures
    :END:

- 3 texts

  - Hebrew Bible: history of development
  - New Testament: Greek to languages of the world
  - Qur'an [[http://www.clearquran.com/][a contemporary web based
    version]]

- God's Word = ?
- definition of Scripture

  - regard a text as *cherished* by a religious community
  - text demanding *devotion*
  - content is somehow understood to be *transcendent*

--

** The Promise and the Heirs
   :PROPERTIES:
   :CUSTOM_ID: the-promise-and-the-heirs
   :END:

- Abraham & the covenant (offspring)
- Hagar & Ishmael (1st born)
- Judaism & Christianity trace heritage to Isaac
- Islam traces heritage to Ishmael (the 1st born)
- History of Israel (cont.)

--------------

** Islam 101
   :PROPERTIES:
   :CUSTOM_ID: islam-101
   :END:

*** RELG 101
    :PROPERTIES:
    :CUSTOM_ID: relg-101
    :END:

*Spring 2017*

- [[https://www.preceden.com/timelines/284990-children-of-abraham][Timeline:]]
- [[http://www.pbs.org/wgbh/globalconnections/mideast/themes/religion/][a
  PBS web site for 3 religions:]]

Note:
[[https://docs.google.com/presentation/d/1LPvGVndUzxRetPnWtANmeXDamChQaiAhe3faaVb6Dzs/edit?usp=sharing][Google
Slides]]

** Presented by WhyIslam.org
   :PROPERTIES:
   :CUSTOM_ID: presented-by-whyislam.org
   :END:

--------------

** Outline
   :PROPERTIES:
   :CUSTOM_ID: outline
   :END:

- Introduction
- Beliefs
- Actions
- Misconceptions

--------------

** Purpose of Life
   :PROPERTIES:
   :CUSTOM_ID: purpose-of-life
   :END:

"And I have not created the jinn and mankind except to worship Me"
(51:56)

[[http://drive.google.com/uc?id=0B8ezT0-tUjVZRWtJOFBITW8xdGM]]

--------------

** What is Islam?
   :PROPERTIES:
   :CUSTOM_ID: what-is-islam
   :END:

| Religion    | Islam         |
|-------------+---------------|
| Belief      | Monotheism    |
| Deity       | Allah (God)   |
| Holy Book   | Qur'an        |
| Prophet     | Mohammad      |

Note:

** Divine Revelation
   :PROPERTIES:
   :CUSTOM_ID: divine-revelation
   :END:

- Sunnah (Prophetic Traditions)
- Sayings, actions or approvals of the Prophet Mohammad (pbuh: /Peace be
  upon him/)

--

** Basis of Islam
   :PROPERTIES:
   :CUSTOM_ID: basis-of-islam
   :END:

| *Qu'ran*            | *Sunnah (Prophetic Traditions)*                                    |
|---------------------+--------------------------------------------------------------------|
| Holy Book           | Sayings, actions                                                   |
| Divine Revelation   | or approvals of the Prophet Mohammad (pbuh): /Peace be upon him/   |

Note: * Seems to come from a non-Muslim perspective * Changed "name of
God" to Deity; put "God" in parenthesis after "Allah" * Maybe the slide
could just have 3 pts (no table) under heading "What is Islam": -
Monotheism (believe Allah), Revealed book = Qur'an, follow Prophet
Muhammad (this approach relates to next slide)

- True Monotheism
- His Name and his oneness
- Try using a table format to organize the content

*Islam* - Submission - Peace - A way of life

--

** Who is a Muslim?
   :PROPERTIES:
   :CUSTOM_ID: who-is-a-muslim
   :END:

"One who submits to God" -- Anyone can become a Muslim -- Common
Greetings incl: /Assalamu Alaykum (Peace be with you)/ & /Wa Alaykum
Assalam (and unto you Peace)/

[[http://drive.google.com/uc?id=0B8ezT0-tUjVZRkg1ZWV4aENvck0]]

Note: * Speaker pt: need to establish definition/distinction of "Islam"
& "Muslim" here so that later slide is indeed a "recap"

Include more relevant pictures that speak to Americans (white) Speaking
Points: Anyone can be a Muslim Include Muslim Greetings

--------------

** What do Muslims Believe?
   :PROPERTIES:
   :CUSTOM_ID: what-do-muslims-believe
   :END:

- Allah
- Angels
- Prophets
- Revelations
- The Hereafter
- Predestination

Note: What about Mozlem or Muzlim (speaking point)

--

** Allah
   :PROPERTIES:
   :CUSTOM_ID: allah
   :END:

- "The ONLY God"
- Characteristics and Names

  - The Most Loving
  - The Most Merciful

/Say: He is Allah, the One and Only; Allah, the Eternal, Absolute; He
begets not, nor is He begotten; And there is none like Him./ Qur'an
112:1-4

--

** Qur'an 2:255
   :PROPERTIES:
   :CUSTOM_ID: quran-2255
   :END:

/Allah! There is no god but He,-the Living, the Self-subsisting,
Eternal. No slumber can seize Him nor sleep. His are all things in the
heavens and on earth. Who is there can intercede in His presence except
as He permitteth? He knoweth what (appeareth to His creatures as) before
or after or behind them. Nor shall they compass aught of His knowledge
except as He willeth. His Throne doth extend over the heavens and the
earth, and He feeleth no fatigue in guarding and preserving them for He
is the Most High, the Supreme (in glory)/.

--

** Angels
   :PROPERTIES:
   :CUSTOM_ID: angels
   :END:

"*They do not disobey Allah's commands and they do as they are told to
do*." (Qur'an 66 verse 6)

| Jibreel   | Gabriel   |
| Mikaeel   | Michael   |

--

** Prophets
   :PROPERTIES:
   :CUSTOM_ID: prophets
   :END:

Chosen by Allah to be His messengers

1. Worship the One true God
2. Accountability

Adam, Abraham, Moses, Jesus, etc...

Mohammad is the final Prophet

--

** Prophet Mohammad (pbuh)
   :PROPERTIES:
   :CUSTOM_ID: prophet-mohammad-pbuh
   :END:

- "Al-Amin" (The Truthful)
- First revelation in Cave Hiraa'
- Preached Islam in Mecca
- Migration to Medina (Islamic society)
- Return to Mecca- Peaceful Conquest

"If greatness of purpose, smallness of means, and astounding results are
the three criteria of human genius, who could dare to compare any great
man in modern history with Muhammad?" *Alphonse de Lamartine*

Note: Condense the next 3 slides to one slide, take out the current
slide and merge with the following slides

Muslim population: 1.61 according to CIA World fact book for 2007 and
1.84 according to www.islamicpopulation.com Largest population of
Muslims is also according to the CIA World Fact Book Arabs are Muslims
-- www.arabicbible.com

--

** Revelations
   :PROPERTIES:
   :CUSTOM_ID: revelations
   :END:

| Arabic     | English      | Prophet    |
| *Suhuf*    | Scriptures   | Abraham    |
| *Tawrah*   | Torah        | Moses      |
| *Zabur*    | Psalms       | David      |
| *Injeel*   | The Gospel   | Jesus      |
| *Qur'an*   | Qur'an       | Mohammad   |

--

**** Qur'an 5:46-48
     :PROPERTIES:
     :CUSTOM_ID: quran-546-48
     :END:

And in their footsteps We sent Jesus the son of Mary, confirming the Law
that had come before him: We sent him the Gospel: therein was guidance
and light, and confirmation of the Law that had come before him: a
guidance and an admonition to those who fear Allah.

Let the people of the Gospel judge by what Allah hath revealed therein.
If any do fail to judge by (the light of) what Allah hath revealed, they
are (no better than) those who rebel.

-- /Continued/

To thee We sent the Scripture in truth, confirming the scripture that
came before it, and guarding it in safety: so judge between them by what
Allah hath revealed, and follow not their vain desires, diverging from
the Truth that hath come to thee. To each among you have we prescribed a
law and an open way. If Allah had so willed, He would have made you a
single people, but (His plan is) to test you in what He hath given you:
so strive as in a race in all virtues. The goal of you all is to Allah;
it is He that will show you the truth of the matters in which ye
dispute;

--

** The Holy Qur'an
   :PROPERTIES:
   :CUSTOM_ID: the-holy-quran
   :END:

- Literally means "The Recited"
- Preserved in its exact original form
- Memorized by over 10 Million
- Contains history, science, prophecies, miracles, inspiration,
  salvation and much more
- A guide on "How to Live"

--------------

#+BEGIN_HTML
  <section data-background="![](http://drive.google.com/uc?id=0B8ezT0-tUjVZMmtJMDdxTXFST28)" data-background-size="1000px">
  </section>
#+END_HTML

Note: * Change 66:6 to "al-Tahrim: verse 6" Many Angels with specific
duties Maybe have a different verse including prostrating to Adam?

Don't spend too much time on this slide

--

** Life after Death
   :PROPERTIES:
   :CUSTOM_ID: life-after-death
   :END:

Accountability -- Weight of Good/Bad Deeds -- Day of Judgment (21:47) --
Heaven -- Hell

[[http://drive.google.com/uc?id=0B8ezT0-tUjVZVllqTFlUeHY2Tkk]]

Note: Prophet -- define who a prophet is Live righteously because we
will be accountable for our deeds... vs. other religions.

--

** Predestination
   :PROPERTIES:
   :CUSTOM_ID: predestination
   :END:

- Certain aspects of one's life are predestined
- Freedom of Choice exists

Note: Try using table format Implement somehow the concept of
progressive revelation. i.e. use numbering and stress in explanation

- Arabic in italics? (more focus on familiar English names + prophets)

--------------

** Duties of a muslim
   :PROPERTIES:
   :CUSTOM_ID: duties-of-a-muslim
   :END:

- What do muslims do
- Actions of a muslim

--

** 5 Pillars Islam
   :PROPERTIES:
   :CUSTOM_ID: pillars-islam
   :END:

| *Shahada*   |              |
| *Salah*     | Prayers      |
| *Zakah*     | Charity      |
| *Sawm*      | Fasting      |
| *Hajj*      | Pilgrimage   |

Note: Minor editing of wording Add 15:9 to this slide (about Allah
protecting the Qur'an)

Revealed over 23 years... explain. Most read and memorzied in the world
10 million -- cite this information Research where the original qur'ans
are Preservation of Arabic language

--

** Shahada
   :PROPERTIES:
   :CUSTOM_ID: shahada
   :END:

*Declaration of Faith*

/La Ilaha Illa Allah Muhammad Rasul-Allah/

"There is no deity worthy of worship except Allah, and Muhammad is the
Final Messenger of Allah"

*Once a person truly believes in the above statement and pronounces it
they become a Muslim.*

Note: Talk about beliefs vs. actions

--

** Salah
   :PROPERTIES:
   :CUSTOM_ID: salah
   :END:

*** Daily Prayers
    :PROPERTIES:
    :CUSTOM_ID: daily-prayers
    :END:

- Muslims pray to God 5 times a day
- Involves Mind, Body and Spirit
- Must be Clean and Pure
- Refreshes ones day

Note: * Changed transliteration to italics

- Changed "worship" to "pray"
- Possible verses: (4:103), (11:114), (17:78-79), (20:130), (2:238)
- Maybe instead of listing the timings, we could list some of the things
  said in prayer (standing, ruku', sujud)

Explain what Islamic Prayer is Find a verse: Indeed prayer will tanha...
(LOOK UP THIS VERSE) Constant relationship with Allah, no intermediaries
Explain duaa vs. prayer and non-mandatory prayers 23 ---

#+BEGIN_HTML
  <section data-background="http://drive.google.com/uc?id=0B8ezT0-tUjVZRWtJOFBITW8xdGM" data-background-size="1000px">
  </section>
#+END_HTML

--------------

** Zakah
   :PROPERTIES:
   :CUSTOM_ID: zakah
   :END:

*** Charity
    :PROPERTIES:
    :CUSTOM_ID: charity
    :END:

- Purifying Wealth
- Mainly to the Poor and Needy
- 2.5% of one's accumulated annual wealth

Note: * Changed wording a bit (shortened as much as possible)

Definition of zakah Amount we pay To whom it can be paid to Compared to
40% tax in this country

--

** Sawm
   :PROPERTIES:
   :CUSTOM_ID: sawm
   :END:

*Fasting*

- Fast during the month of Ramadan
- 30 Days sun up to sun down.

** Benefits**

- Build will-power
- Feel compassion
- Strengthen community bonding

Note: * Possible verse: 2:185 * Don't list so many benefits of fasting
(limit to 3 or 4)- suggest taking out "purifying one's body" * Re-worded
last bullet point

Add Islamic Holiday Primary reason on why we fast. Ordained by god -- if
you fast from something that is ok to do, you won't do anything wrong.
What is included in the fast No one knows that you're fasting, so its
done ONLY for the sake of Allah (swt) Prophets and fasting )i.e David
and how it gets you closer to Allah (swT)

--

** Hajj
   :PROPERTIES:
   :CUSTOM_ID: hajj
   :END:

*** Pilgrimage to Makkah
    :PROPERTIES:
    :CUSTOM_ID: pilgrimage-to-makkah
    :END:

- Once in their lifetime, Muslims travel to Makkah to perform the Hajj.
- The Hajj commemorates the trials of Prophet Abraham and his family.
- About 3-4 million people perform Hajj annually.

Note: Add Islamic Holiday Add the concept of "Ihram" and the ideals
behind it... mention it in the picture as well Add "if they are able"
Benefits: Equality, Patience, Forgiveness Include Malcolm X quote --
concise and short

- Perhaps include less ahadith.

--------------

#+BEGIN_HTML
  <section data-background="http://drive.google.com/uc?id=0B8ezT0-tUjVZQ3ozNFhSTnNZUDQ" data-background-size="1000px">
  </section>
#+END_HTML

--------------

** Islam & Muslim
   :PROPERTIES:
   :CUSTOM_ID: islam-muslim
   :END:

ISLAM =Religion MUSLIM=Follower of Islam

--------------

** A few Misconceptions
   :PROPERTIES:
   :CUSTOM_ID: a-few-misconceptions
   :END:

- Islam and Culture
- Muslims and Arabs
- Status of Women
- Concept of Jihad
- Belief in Jesus

--

** Islam & Culture
   :PROPERTIES:
   :CUSTOM_ID: islam-culture
   :END:

- What's the difference?
- Multiple cultures; Same beliefs

[[http://drive.google.com/uc?id=0B8ezT0-tUjVZbXlYLVZOdzdKcU0]]

--------------

** Muslims and Arabs
   :PROPERTIES:
   :CUSTOM_ID: muslims-and-arabs
   :END:

- Muslim Population 1.6 - 1.8 Billion
- Largest population of Muslims is in Indonesia, India and China
- Arabs only constitute 15-20% of Muslims
- 90-95% of Arabs are Muslims

--

** Status of Women
   :PROPERTIES:
   :CUSTOM_ID: status-of-women
   :END:

"Prior to Islam, a woman was regarded by her parents as a threat to
family honor and hence worthy of burial alive at infancy. As an adult,
she was a sex object that could be bought, sold and inherited. From this
position of inferiority and legal incapacity, Islam raised women to a
position of influence and prestige in family and society." /Cultural
Atlas of Islam/

- Equal vs. Identical
- Examples of Rights 1400 years ago
- Concept of Hijab (Covering)
- Marriage of the Prophet Mohammad (pbuh)

Written on the slide: The Kaabah was built by Abraham and Ishmael as the
first place for people to worship the one God. Video of Hajj: during
prayer

--

** Concept of Jihad
   :PROPERTIES:
   :CUSTOM_ID: concept-of-jihad
   :END:

- Different Forms of Jihad
- Establishment of Justice
- Rules of Engagement
- "Fight in the way of Allah those who fight you but do not transgress.
  Indeed, Allah does not like transgressors" /Qur'an 2:190/

"History makes it clear however, that the legend of fanatical Muslims
sweeping through the world and forcing Islam at the point of the sword
upon conquered races is one of the most fanatically absurd myths that
historians have ever repeated" /De Lacy O'Leary -- Islam at the
Crossroads/

Note: Include Audio of the Qur'an -- Surat Al Fatiha

- This is a 700 year old copy of the Qur'an belonging to Sultan Baybar

--

** Jesus (pbuh)
   :PROPERTIES:
   :CUSTOM_ID: jesus-pbuh
   :END:

- Status in Islam
- Miracles
- Did he die?

"The similitude of Jesus before Allah is as that of Adam He created him
from dust then said to him be and he was" /Qur'an 3: 59/

Note: Some actions of cultures don't represent the teachings of Islam
Pictures of different hijabs (african, arab, etc...)

--

** Shariah
   :PROPERTIES:
   :CUSTOM_ID: shariah
   :END:

- Society
- Economics
- Character of Muslims

In Islam, faith is not an abstract theological dogma, nor an
intellectual creed, nor a philosophical proposition... It is the
Shari`ah which translates faith and moral ideals into clear, definable,
viable, and concrete goals, forms, and codes, and brings them within the
grasp of every ordinary man and woman; this is why it is one of the
greatest blessings of God and one of the greatest vehicles for human
progress. /Khurram Murad/

Note: Bolded & underlined text Maybe take out the writing under each
section (just keep quran and sunnah -- that's it) the rest should be
speaking points.

Maybe title it "Where does it come from?"

--

** Recap slide
   :PROPERTIES:
   :CUSTOM_ID: recap-slide
   :END:

- Belief in One God (Allah)
- Prophet Muhammad was the Final Messenger
- Qur'an is the Final & Preserved Revelation
- Purpose of life is to Worship Allah
- Islam is a Way of Life

--------------

** Hadith
   :PROPERTIES:
   :CUSTOM_ID: hadith
   :END:

*** Sayings of the Prophet Muhammad
    :PROPERTIES:
    :CUSTOM_ID: sayings-of-the-prophet-muhammad
    :END:

"The world is green and beautiful, and God has appointed you His
stewards over it."

"Seeking knowledge is obligatory upon every Muslim (Male and Female)."

"God will show no compassion on the one who has no compassion towards
all humankind."

"God does not look upon your bodies and appearance, He looks upon your
hearts and your deeds."

--

** Hadith (cont)
   :PROPERTIES:
   :CUSTOM_ID: hadith-cont
   :END:

"The most perfect in faith amongst Muslim men is he who is best in
manner and kindest to his wife."

"He who eats his fill while his neighbor goes without food is not a
believer."

Note:

** Any Questions?
   :PROPERTIES:
   :CUSTOM_ID: any-questions
   :END:

Visit www.WhyIslam.org

Or Call (877) Why-Islam
